import type { Metadata } from "next";
import { Noto_Sans_SC } from 'next/font/google'

const inter = Noto_Sans_SC({
  weight: '400',
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>测试{children}</body>
    </html>
  );
}
